directories:
  output: release
  buildResources: public
appId: com.apilot.desktop
productName: ApiLot
files:
  - filter:
      - dist/front-app/browser/**/*
      - electron/**/*
win:
  target: nsis
  icon: public/ApiLot.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerIcon: public/ApiLot.ico
  uninstallerIcon: public/ApiLot.ico
  installerHeaderIcon: public/ApiLot.ico
  createDesktopShortcut: true
  shortcutName: ApiLot
  deleteAppDataOnUninstall: false
  include: build/installer.nsh
extraResources:
  - from: public/ApiLot.ico
    to: public/ApiLot.ico
electronVersion: 37.0.0
